### ISSUE TITLE
Create flag --mark-aligned in __main__.py

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/svgdigitizer#136]
```suggestion
svgdigitizer digitize example_plot_p0_demo.svg --sampling-interval 0.01 --mark-aligned
```

Does not work yet because no such flag is exposed in the CLI.

_Originally posted by @saraedum in https://github.com/echemdb/svgdigitizer/pull/125#discussion_r793226475_

**Comment by DunklesArchipel** [comment]
@saraedum would you rather have a flag `--mark-aligned` or `--algorithm`? The second option seems more intuitive to me.

**Comment by saraedum** [comment]
I think `--algorithm` is a bit strange on the command line. But `--mark-aligned` is also a bit weird because it sounds like it is actually marking something, it sounds like "Mark all aligned things!".

So, maybe `--algorithm` is best after all. There's https://click.palletsprojects.com/en/8.0.x/options/#choice-options which we might want to use here.
