### ISSUE TITLE
Algorithm 'mark-aligned' does not work in combination with an offset of the axis

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/svgdigitizer#138]
When the plot contains a scalebar, which is not perpendicular to the axis without a scalebar (and presumably another scalebar), the data is not extracted properly.

Quickfix:
- [ ] Raise a NotImplementedError when both a scalebar and a algorithm is set to 'mark-aligned' 
Or:
- [ ] Fix the issue. :)

**Comment by saraedum** [comment]
Do you have an example where this fails? The output in https://github.com/echemdb/svgdigitizer/pull/139 looks correct to me.

**Comment by DunklesArchipel** [comment]
Consider the two tests included in #137 
1. scaling_factor.svg
2. scaling_factor_skewed.svg

In 1. the scalebar is almost vertical (dotted lines a re a guide to the eye):
![image](https://user-images.githubusercontent.com/39313137/152593628-c0f87d6d-32af-498f-9f70-8e62abef3e86.png)

In 2. I tilted the scalebar slightly clockwise.
![image](https://user-images.githubusercontent.com/39313137/152593764-e644a053-f104-4e12-98f3-f82d5fd1f27a.png)

This should lead to a small shift of the figure to the left (or the vertical axis is rotated counterclockwise, whatever you want to call it). This is, however, the result:
![image](https://user-images.githubusercontent.com/39313137/152594131-5847bf71-f251-4848-8ddc-3f718327eee5.png)

**Comment by saraedum** [comment]
Let me try to explain how this is supposed to work. We fixed four points. Two points on the x-axis called x₁ and x₂ and two points on the y-axis called y₁ and y₂.

(*) We know the x-value of x₁ and x₂ and we know that they have the same y-value (because they are on the x-axis) but we do not make any assumption on that value, just that it's the same. In the same way we know the y-value of y₁ and y₂ and we know that they have the same x-value.

Let's illustrate what we have so far with one of the cases that @linuxrider used in the PR #139:

![broken-1](https://user-images.githubusercontent.com/373765/158717441-2cfefa97-6537-401a-becf-deb02e68eb45.svg)

(**) We'll now assume that our picture is linear, i.e., that any two points that differ by the vector from x₁ to x₂ differ by 1.5V on the x-axis and do not differ on the y-axis. And in the same way, any two points that differ by the vector from y₁ to y₂ differ by 50µA/cm² and do not differ on the x-axis.

![broken-3](https://user-images.githubusercontent.com/373765/158719333-433926a3-a754-4129-9542-c3baa10d1a63.svg)

Everything that follows is a consequence of (*) and (**). We have now essentially no choice anymore (ok, that's actually a lie but it's true if we assume that x₁ and x₂ are not the same point, y₁ and y₂ are not the same point and the four points do not fall on a single one-dimensional line…so, for all practical purposes, there is no choice now anymore.) The only meaningful choice that we would have had until now is to replace (**) with the assumption that only the x-portion of the arrow x₁ → x₂ is relevant and only the y-portion of the arrow y₁→y₂ is relevant. This is exactly what `axis-aligned` does.

Let's add some axes. What is an axis? Well, an x-axis is a line where all points have the same y-value (typically 0 but we won't do that here) and a y-axis is a line where all points have the x-value. We know two pairs of such points so drawing a line through them gives us an axis.

![broken-2](https://user-images.githubusercontent.com/373765/158718079-9126c5a5-bcb8-4e30-a7cf-81954fec89a3.svg)

These axes are not orthogonal of course. (Our coordinate system is not Cartesian.)

Now we can read off the coordinate of any point, let's say one of the peaks. We can for example get the coordinate of a point by moving each axis along the other axis until the point is the intersection point. (Note that moving the axes in this way does not change them because we assumed that moving in the directions of the arrows does not change the value on the other axis.)

![broken-4](https://user-images.githubusercontent.com/373765/158720803-f2eb3d56-640d-4326-b15f-ba0c1bfbec92.svg)

We get about (-.75V, 100μA) for the point. Which (after applying the scaling factor) roughly matches what svgdigitizer found here.

**Comment by saraedum** [comment]
> This should lead to a small shift of the figure to the left (or the vertical axis is rotated counterclockwise, whatever you want to call it). This is, however, the result:

As I tried to illustrate it leads to a skew of the plot. I think what you are observing is the correct expected behaviour.

**Comment by linuxrider** [comment]
Your are right. The unexpected behavior is caused by artificial examples. In real world it works.

**Comment by saraedum** [comment]
So. I think this can be closed.
