### ISSUE TITLE
False exported values caused by units

### ISSUE THREAD

**Issue by FMMechem** [echemdb/svgdigitizer#165]
When exporting CV data with the coordinate system label "j1: µA cm^-2", the exported data does not match the data in the figure. With "j1: A" the correct data is exported. With "j1: µA" the data are exported with a division factor of 10^6.

Attached are three .svg data with "j1: µA cm^-2", "j1: A" and "j1: µA".
.csv created with `svgdigitizer cv --sampling-interval=0.001 filename.svg`

![µA](https://user-images.githubusercontent.com/123760456/215148315-4ec04092-d891-420c-9e9d-58c7f8589291.svg)
![µAcm-2](https://user-images.githubusercontent.com/123760456/215148318-03aa2008-8981-4bc4-8fd9-781aefd3812c.svg)
![A](https://user-images.githubusercontent.com/123760456/215148321-1d968fa3-5aa6-4f81-8e15-1f2c4222acdc.svg)

**Comment by DunklesArchipel** [comment]
@FMMechem the factor you observe is actually intentional since the exported data is in **SI units**. We apologize that this is not clearly documented. 
Since the CSV only contains dimensions as column headers it seems to be reasonable to assume that the underlying data is in SI units. In the JSON created along with the data, both the original axis units are found in the `figure_description` section and the exported units in the `data_decsription` section.

**Comment by linuxrider** [comment]
@DunklesArchipel Actually, I was hit by this, too. Several times. Even I should how works.
Can we have a flag which sets the output to SI units? e.g `--si`

**Comment by DunklesArchipel** [comment]
That sounds like a good idea, especially since the regular digitizing option (not cv) does not have an option for SI conversion.

**Comment by DunklesArchipel** [comment]
Fixed in #178
