### ISSUE TITLE
Add export functionality to DataPackage?

### ISSUE THREAD

**Issue by nicohoermann** [echemdb/svgdigitizer#72]
For compatibility with DataPackage: I think we could/should have a def export_to_datapackage as a functionality of cv. If we just export json identical to yaml we need to create another json for datapackage descriptor.

I have a running version which does according task: export .json, and .csv but fullfilling datapackage criteria and keeping all the yaml information. 

We could also keep datapackage in website and then transform initial .json to datapackage descriptor json. Seems too complicated??!

Shall I pull request?

**Comment by DunklesArchipel** [comment]
In principle, the `svgdigitizer` should be decoupled from the website. Hence the `cv` function from the CLI is a nice way for someone who simply wants to digitize CVs for his own purpose. 

The data package you are talking about should be created in the `website` repo. As far as I recall, we want to upload the scvgfile and the yaml file as pull request on the website. The datapackage is then created via Github actions, when the data is merged. So basically you do not have to execute the code locally.

In order to do so, there should probably be a module named `datapackage.py` in `echemdb/website`.

**Comment by saraedum** [comment]
It feels easier to me to add this to the `cv` module. Just a flag `--export-datapackage` that creates .json and .csv instead of .yaml and .csv. Of course it's a bit specific to the website but then again datapackages try to be a standard for these kinds of things so it does not seem to crazy that the digitizer can produce that format.

**Comment by DunklesArchipel** [comment]
see #79
